cli-wallet:
  image: bitshares/bitshares-2-cli-wallet
  volumes:
    - ./wallet:/wallet
    - ./cli-wallet-start.sh:/start.sh

exchange-bot:
  image: exchangebot
  volumes:
    - ./docker-exchangebot:/usr/src/app
  links:
    - cli-wallet
